// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRIjzylkBqTAdp5bv_rJLjc_XaWsXAg0o',
    appId: '1:604843338201:web:f25cc2faca09f373ec91c8',
    messagingSenderId: '604843338201',
    projectId: 'notes2-flutter-tuto',
    authDomain: 'notes2-flutter-tuto.firebaseapp.com',
    storageBucket: 'notes2-flutter-tuto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPKbnu07Hm97buBhyZcwvlvtEdmr2bUZI',
    appId: '1:604843338201:android:50a0d7b069aa0730ec91c8',
    messagingSenderId: '604843338201',
    projectId: 'notes2-flutter-tuto',
    storageBucket: 'notes2-flutter-tuto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMMwRF5LBqcqGokkGP4gy_r4Q53s-Jyz4',
    appId: '1:604843338201:ios:4fc97e086531bfd9ec91c8',
    messagingSenderId: '604843338201',
    projectId: 'notes2-flutter-tuto',
    storageBucket: 'notes2-flutter-tuto.appspot.com',
    iosClientId: '604843338201-29qfitnbo21uv6qihb0rkkpqitao30v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMMwRF5LBqcqGokkGP4gy_r4Q53s-Jyz4',
    appId: '1:604843338201:ios:4fc97e086531bfd9ec91c8',
    messagingSenderId: '604843338201',
    projectId: 'notes2-flutter-tuto',
    storageBucket: 'notes2-flutter-tuto.appspot.com',
    iosClientId: '604843338201-29qfitnbo21uv6qihb0rkkpqitao30v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes2',
  );
}
